import { useEffect, useState } from "react";
import { Panel } from "../components/Primitive.js";
import { WorkspaceHeader } from "../components/WorkspaceHeader.js";

type SavedCommunity = Awaited<ReturnType<typeof window.peerHours.listCommunities>>[number];

/** Lets a member create or join a self-certifying community scope without relying on a central directory. */
export function CommunitiesPage() {
  const [communities, setCommunities] = useState<readonly SavedCommunity[]>([]);
  const [name, setName] = useState(""); const [locality, setLocality] = useState(""); const [region, setRegion] = useState(""); const [country, setCountry] = useState("");
  const [invitation, setInvitation] = useState(""); const [createdInvitation, setCreatedInvitation] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [working, setWorking] = useState(false);
  /** Refreshes only the local device's verified community choices. */
  const refresh = async () => { try { setCommunities(await window.peerHours.listCommunities()); } catch { setMessage("Your saved communities could not be read on this device."); } };
  useEffect(() => { void refresh(); }, []);
  /** Creates a signed genesis feed and exposes an invitation for an intentional out-of-band handoff. */
  const create = async (event: React.FormEvent) => { event.preventDefault(); setWorking(true); setMessage(null); try { const result = await window.peerHours.createCommunity({ displayName: name, locality, ...(region.trim() ? { region } : {}), country }); setCreatedInvitation(result.invitation); setMessage(`“${result.genesis.displayName}” is ready on this device. Share its invitation with another peer to make it available beyond this device.`); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The community could not be created."); } finally { setWorking(false); } };
  /** Verifies a copied invitation against the remote genesis record before saving the scope locally. */
  const join = async (event: React.FormEvent) => { event.preventDefault(); setWorking(true); setMessage(null); try { const genesis = await window.peerHours.joinCommunity(invitation); setMessage(`Joined “${genesis.displayName}”. This device now trusts its signed genesis record.`); setInvitation(""); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The community invitation could not be verified."); } finally { setWorking(false); } };
  return <section className="communities-page"><WorkspaceHeader eyebrow="Communities" title="Choose where you participate" description="A community is a shared discovery scope, not an account managed by a central service. Create one with another online peer, or join from an invitation you trust." />{message && <p className="notice" role="status">{message}</p>}<div className="communities-page__grid"><Panel><span className="kicker">Create a community</span><h2>Start a shared scope</h2><p>Creation requires an active peer connection. Peer Hours writes an immutable, root-signed genesis record on this device; keep a second peer online to receive the invitation and replicate it.</p><form className="community-form" onSubmit={(event) => void create(event)}><label>Community name<input value={name} onChange={(event) => setName(event.target.value)} required maxLength={120} /></label><label>Locality<input value={locality} onChange={(event) => setLocality(event.target.value)} required maxLength={120} /></label><label>Region (optional)<input value={region} onChange={(event) => setRegion(event.target.value)} maxLength={120} /></label><label>Country<input value={country} onChange={(event) => setCountry(event.target.value)} required maxLength={120} /></label><button disabled={working} type="submit">Create signed community</button></form>{createdInvitation && <label className="community-invitation">Invitation<textarea readOnly value={createdInvitation} aria-label="Community invitation" /></label>}</Panel><Panel><span className="kicker">Join a community</span><h2>Verify an invitation</h2><p>Joining fetches the genesis feed, verifies its creator signature, and confirms the discovery key before this device trusts the community.</p><form className="community-form" onSubmit={(event) => void join(event)}><label>Invitation<textarea value={invitation} onChange={(event) => setInvitation(event.target.value)} required /></label><button disabled={working} type="submit">Verify and join</button></form></Panel></div><Panel className="communities-page__saved"><span className="kicker">Saved on this device</span><h2>Your verified communities</h2>{communities.length === 0 ? <p>No community has been created or joined on this device yet.</p> : <ul>{communities.map((community) => <li key={community.genesis.communityId}><strong>{community.genesis.displayName}</strong><span>{community.genesis.location ? `${community.genesis.location.locality}, ${community.genesis.location.country}` : "No location provided"}</span><code>{community.genesis.communityId}</code></li>)}</ul>}</Panel></section>;
}
